// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPszACnxqDxNasnF9-D33UrmrhsdGqKKE',
    appId: '1:283704459158:web:0490260cdb68624f91a7b7',
    messagingSenderId: '283704459158',
    projectId: 'test-7fe47',
    authDomain: 'test-7fe47.firebaseapp.com',
    storageBucket: 'test-7fe47.appspot.com',
    measurementId: 'G-XHVHS911WZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4JPxPXrNCqPvwNi746mBUoex0qJirww',
    appId: '1:283704459158:ios:a56e6222b5c15c8c91a7b7',
    messagingSenderId: '283704459158',
    projectId: 'test-7fe47',
    storageBucket: 'test-7fe47.appspot.com',
    androidClientId: '283704459158-mjskm230pb45tngeifj9rvapt22c1953.apps.googleusercontent.com',
    iosClientId: '283704459158-vhennvmbcn8vbim44942ljerbk65hb17.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonorDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPszACnxqDxNasnF9-D33UrmrhsdGqKKE',
    appId: '1:283704459158:web:318051f7bf554e4291a7b7',
    messagingSenderId: '283704459158',
    projectId: 'test-7fe47',
    authDomain: 'test-7fe47.firebaseapp.com',
    storageBucket: 'test-7fe47.appspot.com',
    measurementId: 'G-5ENNC6HGD5',
  );
}
